# ==========================================================================
# The .zshrc file is generated by the setup script with a dynamic $PATH
# This .zprofile file is registered before .zshrc, so sourcing .zshrc first


echo ".zprofile:  loading..."

# Doesn't seem like there is a need to source this file?
# if [ -f ~/.zshrc ]; then
#     echo ".zprofile:  Sourcing the .zshrc file..."
#     source ~/.zshrc
# fi

## ================================================================================
# Welcome to the shell message
TIMENOW=$(date +%d-%m-%Y" "%H:%M:%S)
echo ".zprofile:  Using '$SHELL' shell. Launched at ${TIMENOW}."

