# ==========================================================================
# The .zshrc file is generated by the setup script with a dynamic $PATH
# This .zprofile file is registered before .zshrc, so sourcing .zshrc first

if [ -f ~/.zshrc ]; then
    source ~/.zshrc
    echo "Sourced (imported) the .zshrc file successfully."
fi

## ================================================================================
# Welcome to the shell message
TIMENOW=$(date +%d-%m-%Y" "%H:%M:%S)
echo "> Using '$SHELL' shell. This is the .zprofile file. Launched at ${TIMENOW}."
echo

